# The list of Trigger events https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
name: 05 Events

on:
  pull_request:
    types: [ opened, reopened]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -1
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_RUN_ID
      - name: Cheeckouts
        uses: actions/checkout@v2