name: 04 Github Cheeckouts

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -1
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_RUN_ID
      - name: Cheeckouts
        uses: actions/checkout@v2





